const Autores = [
    "Paulo Coelho",
    "Oscar Wilde",
    "Douglas Crockford",
    "Robert Louis Stevenson",
    "F. Scott Fitzgerald",
    "Mary Shelley",
    "Patrick Rothfuss",
    "Jane Austen",
    "Robert C. Martin",
    "Harper Lee",
    "Miguel de Cervantes",
    "J.R.R. Tolkien",
    "Arthur Conan Doyle",
    "George Orwell",
    "Ernest Hemingway",
    "Carlos Ruiz Zafón",
    "Dan Brown",
    "J.K. Rowling",
    "J.D. Salinger",
    "León Tolstói",
    "Herman Melville",
    "Brian W. Kernighan, Dennis M. Ritchie",
    "Torcuato Luca de Tena",
    "Victor Hugo",
    "Gabriel García Márquez",
    "Daniel Defoe",
    "Eric Matthes",
    "Antoine de Saint-Exupéry",
    "Homero",
    "Julio Cortázar",
    "Bram Stoker",
    "Julio Verne",
    "Louisa May Alcott",
    "Fiodor Dostoievski",
    "Franz Kafka",
    "Mario Vargas Llosa"
  ];

  export default Autores;