const Editoriales = [
    "Bloomsbury Publishing",
    "Editorial Planeta",
    "Longmans, Green & Co.",
    "Editorial Sudamericana",
    "J.B. Lippincott & Co.",
    "T. Egerton, Whitehall",
    "Juan de la Cuesta",
    "George Allen & Unwin",
    "Prentice Hall",
    "Kurt Wolff Verlag",
    "DAW Books",
    "A. Lacroix, Verboeckhoven & Cie",
    "Secker & Warburg",
    "Editorial Oveja Negra",
    "Reynal & Hitchcock",
    "Doubleday",
    "HarperCollins",
    "Iberica",
    "Ward, Lock and Co.",
    "George Newnes Ltd",
    "Lackington, Hughes, Harding, Mavor & Jones",
    "Richard Bentley",
    "Archibald Constable and Company",
    "Pierre-Jules Hetzel",
    "The Russian Messenger",
    "Charles Scribners Sons",
    "Robert Brothers",
    "W. Taylor",
    "Alianza Editorial",
    "Cassell & Co.",
    "Seix Barral",
    "Plaza & Janés",
    "Prentice Hall",
    "O'Reilly Media",
    "No Starch Press"
  ];

  export default Editoriales;